" An example for a vimrc file.
"
" Maintainer:	The Vim Project <https://github.com/vim/vim>
" Last Change:	2023 Aug 10
" Former Maintainer:	Bram Moolenaar <Bram@vim.org>
"
" To use it, copy it to
"	       for Unix:  ~/.vimrc
"	      for Amiga:  s:.vimrc
"	 for MS-Windows:  $VIM\_vimrc
"	      for Haiku:  ~/config/settings/vim/vimrc
"	    for OpenVMS:  sys$login:.vimrc

" When started as "evim", evim.vim will already have done these settings, bail
" out.
if v:progname =~? "evim"
  finish
endif

" Get the defaults that most users want.
source $VIMRUNTIME/defaults.vim

if has("vms")
  set nobackup		" do not keep a backup file, use versions instead
else
  set backup		" keep a backup file (restore to previous version)
  if has('persistent_undo')
    set undofile	" keep an undo file (undo changes after closing)
  endif
endif

if &t_Co > 2 || has("gui_running")
  " Switch on highlighting the last used search pattern.
  set hlsearch
endif

" Put these in an autocmd group, so that we can delete them easily.
augroup vimrcEx
  au!

  " For all text files set 'textwidth' to 78 characters.
  autocmd FileType text setlocal textwidth=78
augroup END

" Add optional packages.
"
" The matchit plugin makes the % command work better, but it is not backwards
" compatible.
" The ! means the package won't be loaded right away but when plugins are
" loaded during initialization.
if has('syntax') && has('eval')
  packadd! matchit
endif


set nocopyindent
set preserveindent
set nosmarttab
"https://stackoverflow.com/questions/607435/why-does-vim-save-files-with-a-extension
set nobk nowb noswf noudf " nobackup nowritebackup noswapfile noundofile
set noeb vb t_vb= " errorbells visualbell
set number
set norelativenumber
set nocompatible
"filetype plugin indent on
set autoindent
set nosmartindent
set nocindent
"https://vimrcfu.com/snippet/126
" Disable automatic label dedent.
" Can also be set in ~/.vim/after/ftplugin/cpp.vim
autocmd FileType cpp setlocal cinoptions+=L0
"found in /usr/share/vim/vim91/ftplugin
au FileType html,htmldjango setlocal indentkeys=
set noexpandtab "Preserve tabs for filetypes that are not special
